# Generated by Django 4.2.7 on 2026-01-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0011_alter_order_estimated_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'liquor Categories'},
        ),
        migrations.AddField(
            model_name='order',
            name='is_test_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foodcategory',
            name='store_type',
            field=models.CharField(choices=[('food', 'Food Store'), ('liquor', 'Liquor Store'), ('grocery', 'Grocery Shop')], default='liquor', max_length=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='store_type',
            field=models.CharField(choices=[('food', 'Food Store'), ('liquor', 'Liquor Store'), ('grocery', 'Grocery Shop')], default='liquor', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='store_type',
            field=models.CharField(choices=[('food', 'Food Store'), ('liquor', 'Liquor Store'), ('grocery', 'Grocery Shop')], default='liquor', max_length=10),
        ),
    ]
