# Generated by Django 4.2.7 on 2026-01-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0012_alter_foodcategory_options_order_is_test_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Food Categories'},
        ),
    ]
