# Generated by Django 4.2.7 on 2026-01-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0013_alter_foodcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategory',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Available stock for this category (for liquor store)'),
        ),
    ]
