# Generated by Django 4.2.7 on 2026-02-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0014_foodcategory_stock_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Liquor Categories'},
        ),
    ]
