# Generated by Django 4.2.7 on 2026-02-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0015_alter_foodcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodcategory',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert when stock goes below this number'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available units in stock'),
        ),
    ]
