# Generated by Django 4.2.7 on 2026-02-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0016_remove_foodcategory_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=2, help_text='Alert when stock goes below this number'),
        ),
    ]
