# Generated by Django 4.2.7 on 2026-02-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0019_mpesatransaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='event_type',
            field=models.CharField(choices=[('stk_initiated', 'STK Initiated'), ('callback_received', 'Callback Received'), ('stk_query', 'STK Query')], default='stk_initiated', max_length=30),
        ),
    ]
