# Generated by Django 4.2.7 on 2026-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0020_mpesatransaction_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodreview',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
