# Generated by Django 4.2.7 on 2026-02-19 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0021_foodreview_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodreview',
            name='average_rating',
        ),
    ]
