# Generated by Django 4.2.7 on 2026-02-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0022_remove_foodreview_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_reviewed_items',
            field=models.BooleanField(default=False),
        ),
    ]
