# Generated by Django 6.0.3 on 2026-04-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0023_order_has_reviewed_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, help_text='Last time review prompt was dismissed', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='review_prompted_count',
            field=models.IntegerField(default=0, help_text='Number of times review prompt has been shown'),
        ),
    ]
