# Generated by Django 6.0.3 on 2026-05-19 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanfoods', '0026_alter_sitesettings_delivery_fee_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryGuyWeeklyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Start date of the week')),
                ('week_end', models.DateField(help_text='End date of the week')),
                ('deliveries_count', models.IntegerField(default=0, help_text='Number of deliveries for the week')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue for the week', max_digits=10)),
                ('is_paid', models.BooleanField(default=False, help_text='Whether the payment has been marked as completed')),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the payment was marked as completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_guy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_payments', to='urbanfoods.deliveryguy')),
            ],
            options={
                'verbose_name': 'Delivery Guy Weekly Payment',
                'verbose_name_plural': 'Delivery Guy Weekly Payments',
                'ordering': ['-week_start'],
                'unique_together': {('delivery_guy', 'week_start', 'week_end')},
            },
        ),
    ]
